Metrics/AbcSize:
  Max: 36

Metrics/ClassLength:
  Max: 199

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Max: 117

Metrics/MethodLength:
  Max: 38

Metrics/ParameterLists:
  Max: 8

Style/SpecialGlobalVars:
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  Exclude:
    - 'bin/gherkin_language'
    - 'lib/gherkin_language/language_tool_process.rb'
