#!/bin/bash
set -e

function gather_tags {
  curl -fqs https://www.languagetool.org/download/ | grep 'LanguageTool-[0-9].*zip' | sed 's/.*>LanguageTool-\(.*\)\.zip.*/\1/' | sort
}

LATEST_TAG=$(gather_tags | tail -n 1)
sed -i "s/VERSION \= 'LanguageTool-.*'/VERSION = 'LanguageTool-${LATEST_TAG}'/" lib/gherkin_language/language_tool_process.rb

git add lib/gherkin_language/language_tool_process.rb
git commit -m 'Using Languagetool ${LATEST_TAG}'
git push
